### ISSUE TITLE
Support py 3.7

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-citeit#12]
Looks like the build for Python 3.4 is now failing. I think we can remove support for that and add a build for Python 3.7 and make sure it works in that version.

**Comment by madhulika95b** [comment]
when the version of python version is 3.7 in travis, python 3.6 tests are failing with Interpreter not found error. Do you think I can remove py3.6 as well..? But the tox tests are passing for py3.6 locally.

**Comment by ldko** [comment]
I think we should be able to get tests to run for both py3.6 and 3.7 in Travis. You had them both working for django-edtf I think; did you look at what is different from that repo?

**Comment by madhulika95b** [comment]
I think, there I have added the python interpreters separately for every testing env. I can do the same here. Umm...what about django 1.10? Do you think I can get rid of testing it since it isn't supported by django anymore?

**Comment by ldko** [comment]
Yeah, we could get rid of testing Django 1.10

**Comment by ldko** [comment]
Done in https://github.com/unt-libraries/django-citeit/pull/13.
