### ISSUE TITLE
regexes in urls.py are too strict

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-citeit#3]
Because of the way the regular expressions are given for the urls, look ups are 404ing when they shouldn't. For example: a degree abbreviation has an apostrophe like "master's" or an author name has a hyphen, institution has ampersand like "M&M", etc.

**Comment by somexpert** [comment]
I agree there are problems with the institution url and the author url, but for the institution abbreviation, it should always just be characters. Something like `master's` wouldn't be in the url, since the lookup is done on the abbreviation (MBA, PHD), not the actual degree name.

**Comment by ldko** [comment]
Is it defined somewhere what is considered valid for that field? What you are saying makes sense, so if there are some rules about what should be allowed for certain fields, at some point, some form field validation should be introduced because it will accept "master's" as an abbreviation and store it in the database--if it shouldn't be allowed, it shouldn't accept it in the first place.

**Comment by somexpert** [comment]
Yeah, that is the case for several of the fields in the models. I'll add expected fail tests that cover those occurrences.
